# Generated by Django 4.1.7 on 2023-03-24 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_orderlines_delete_orderlines'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernumber', models.IntegerField()),
                ('orderlinenumber', models.IntegerField()),
                ('productcode', models.TextField()),
                ('productname', models.TextField()),
                ('customerid', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('productid', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Order_OrderLines',
        ),
    ]
